on: 
  push:
    branches: [ master ]
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.11
      with:
        github_token: 2e6c477cf8b2f6ce79223b9426a71a491ef45d5c 
        goos: linux
        goarch: amd64
