on: 
  release:
    types: [created]
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.11
      with:
        github_token: ${{ secrets.publish_key}}
        goos: linux
        goarch: amd64
        release_tag: beta
